export enum ERROR_CODE {
  ABYSS_KAFKA_CLUSTER_IS_INVALID = 'Kafka кластер недействителен',
  ABYSS_GRANT_NOT_FOUND = `Права у %u не найдены`,
  ABYSS_PROJECT_NOT_FOUND = `Проект %p не найден.`,
  ABYSS_GROUP_NOT_FOUND = `Группа %g не найдена.`,
  ABYSS_USER_NOT_FOUND = `Пользователь %u не найден.`,
  ABYSS_SEARCH_PATTERN_NOT_FOUND = `Поисковой паттерн %i не найден.`,
  ABYSS_FULLTEXT_INDEX_NOT_FOUND = `Полнотекстовый индекс %i не найден.`,
  ABYSS_FULLTEXT_INDEX_COLLECTION_NOT_FOUND = 'Указанная коллекция полнотекстового индекса не найдена.',
  ABYSS_SEARCH_PATTERN_MATCHED_FULLTEXT_INDEX_NOT_FOUND = 'Полнотекстовый индекс по шаблону не найден',
  ABYSS_QUOTA_NOT_FOUND = `Квота для ресурса не найдена.`,
  ABYSS_DICTIONARY_NOT_FOUND = `Словарь %i не найден.`,
  ABYSS_LOOKUP_NOT_FOUND = `Lookup %i не найден.`,
  ABYSS_DICTIONARY_COLUMN_NOT_FOUND = `Колонка словаря %i не найдена.`,
  ABYSS_ANALYTICAL_INDEX_NOT_FOUND = `Аналитический индекс %i не найден.`,
  ABYSS_ARCHIVE_INDEX_NOT_FOUND = `Архив %i не найден.`,
  ABYSS_QUERY_NOT_FOUND = `Запрос не найден.`,
  ABYSS_KAFKA_TOPIC_NOT_FOUND = `Топик(-и) Kafka %t не найден(-ы).`,
  ABYSS_FLOW_NOT_FOUND = `Поток %i не найден.`,
  ABYSS_DRUID_TASK_NOT_FOUND = `Задача Druid не найдена.`,
  ABYSS_URL_HANDLER_NOT_FOUND_ERROR = `У данного URL нет соответствующего обработчика.`,
  ABYSS_GRANT_ALREADY_EXISTS = `Права уже выданы`,
  ABYSS_AUTHORIZATION_IS_MISSING = `Заголовок Authorization пустой.`,
  ABYSS_TOKEN_XSS_VALIDATION_ERROR = `Включена XSS валидация и claims невалидный.`,
  ABYSS_TOKEN_SIGNATURE_IS_INVALID = `Валидный токен с неверной подписью.`,
  ABYSS_TOKEN_CLAIMS_ARE_INVALID = `Валидный токен, но claims неверный.`,
  ABYSS_TOKEN_IS_INVALID = `Невалидная структура токена.`,
  ABYSS_CREDENTIALS_ARE_INVALID = `Неверный логин/пароль.`,
  ABYSS_AUTHORIZATION_NOT_SUPPORTED = `Запрос с неверной схемой аутентификации.`,

  ABYSS_ADMIN_PRIVILEGES_REQUIRED = `Для выполнения операции управления правами требуются права администратора.`,
  ABYSS_ACCESS_DENIED_TO_ANALYTICAL_INDEX = `Доступ до аналитического индекса %i запрещен.`,
  ABYSS_ACCESS_DENIED_TO_PROJECT = `Доступ до проекта %p запрещен.`,
  ABYSS_ACCESS_DENIED_TO_LOOKUP = `Доступ до lookup'a %i запрещен.`,
  ABYSS_ACCESS_DENIED_TO_ARCHIVE_INDEX = `Доступ до архива %i запрещен.`,
  ABYSS_ACCESS_DENIED_TO_FLOW = `Доступ до потока %i запрещен.`,
  ABYSS_ACCESS_DENIED_TO_SEARCH_PATTERN = `Доступ до поискового паттерна %i запрещен.`,
  ABYSS_ACCESS_DENIED_TO_KAFKA_TOPIC = `Доступ до топика Kafka %t запрещен.`,
  ABYSS_ACCESS_DENIED_TO_FULL_TEXT_INDEX = `Доступ до полнотекстового индекса %i запрещен.`,
  ABYSS_ACCESS_DENIED_TO_GROUP = `Доступ до группы %g запрещен.`,
  ABYSS_ACCESS_DENIED_TO_OPERATION = `Недостаточно прав для выполнения этой операции.`,
  ABYSS_ACCESS_DENIED_TO_RESOURCE = `Недостаточно прав для доступа к данному ресурсу.`,

  ABYSS_PROJECT_ALREADY_EXISTS = `Проект с таким именем уже существует.`,
  ABYSS_GROUP_ALREADY_EXISTS = `Группа с таким именем уже существует.`,
  ABYSS_USER_ALREADY_EXISTS = `Пользователь с таким именем уже существует.`,
  ABYSS_USER_ALREADY_HAS_GRANT = `Пользователь уже получил права`,
  ABYSS_SEARCH_PATTERN_ALREADY_EXISTS = `Поисковой паттерн с таким именем уже существует.`,
  ABYSS_DICTIONARY_ALREADY_EXISTS = `Словарь с таким именем уже существует.`,
  ABYSS_LOOKUP_ALREADY_EXISTS = `Lookup с таким именем уже существует.`,
  ABYSS_ANALYTICAL_INDEX_ALREADY_EXISTS = `Аналитический индекс с таким именем уже существует.`,
  ABYSS_ARCHIVE_INDEX_ALREADY_EXISTS = `Архивный индекс с таким именем уже существует.`,
  ABYSS_SOURCE_ALREADY_EXISTS = `Источник данных с таким именем уже существует.`,
  ABYSS_KAFKA_TOPIC_ALREADY_EXISTS = `Топик Kafka с таким именем уже существует.`,
  ABYSS_FLOW_PARALLEL_UPDATE = `Совершена попытка параллельного обновления потока. Попробуйте позже.`,
  ABYSS_FULLTEXT_INDEX_ALREADY_EXISTS = `Полнотекстовый индекс с таким именем уже существует.`,
  ABYSS_RESOURCE_ALREADY_SHARED = `Данный ресурс уже является публичным.`,

  ABYSS_SEARCH_PATTERN_RENAMING_FORBIDDEN = `Нельзя изменять имя поискового паттерна.`,
  ABYSS_ANALYTICAL_INDEX_RENAMING_FORBIDDEN = `Нельзя изменять имя аналитического индекса.`,
  ABYSS_ARCHIVE_INDEX_RENAMING_FORBIDDEN = `Нельзя изменять имя архивного индекса.`,
  ABYSS_KAFKA_TOPIC_REPLICATION_CHANGING_FORBIDDEN = `Нельзя изменять количество репликаций у Kafka топика.`,
  ABYSS_KAFKA_PARTITIONS_COUNT_DECREASING_FORBIDDEN = `Нельзя уменьшать количество партиций в Kafka.`,
  ABYSS_SUBJECT_ALREADY_BLOCKED = `Данный объект уже имеет блокировку`,
  ABYSS_FLOW_ALREADY_STARTED = `Поток уже стартовал.`,
  ABYSS_FLOW_ALREADY_EXISTS = `Поток с таким именем уже существует.`,
  ABYSS_FLOW_OPERATION_UNAVAILABLE = `Недоступная операция для потока.`,
  ABYSS_SUPERVISOR_NOT_FOUND = `Supervisor не найден.`,

  ABYSS_ANALYTICAL_INDEX_IS_NOT_ACTIVE = `Аналитический индекс %i уже неактивен.`,
  ABYSS_FLOW_ALREADY_RUNNING = `Поток %i уже был запущен или не полностью остановлен.`,
  ABYSS_DICTIONARY_IN_USE = `Словарь %i нельзя удалить, так как он используется.`,
  ABYSS_QUOTA_DECREASING_ERROR = `Нельзя уменьшить квоту. Введенное Вами значение меньше, чем уже занятое место.`,
  ABYSS_LOOKUP_COUNT_DECREASING_ERROR = `Нельзя уменьшать количество lookup'ов. Lookup'ов уже создано больше, чем указанное Вами число.`,
  ABYSS_FULLTEXT_INDEX_WRONG_TYPE = `Нельзя изменять тип индекса.`,
  ABYSS_FULLTEXT_INDEX_UNPROCESSABLE_ROTATION = `Введены некорректные параметры ротации.`,

  ABYSS_KAFKA_ACL_IS_DISABLED = `ACL выключен.`,
  ABYSS_KAFKA_ACL_ERROR = 'Ошибка с ACL.',
  ABYSS_KAFKA_ACL_ALREADY_EXIST = 'ACL уже существует.',
  ABYSS_SEARCH_PATTERN_WILDCARD_IS_DISABLED = `В поисковых паттернах нельзя использовать wildcard "*".`,
  ABYSS_KAFKA_ACL_WILDCARD_IS_DISABLED = `В ACL Kafka нельзя использовать wildcard "*".`,

  ABYSS_QUOTA_EXCEEDED_FOR_FULLTEXT_INDEX = `Квота на полнотекстовый индекс превышена.`,
  ABYSS_QUOTA_EXCEEDED_FOR_KAFKA_TOPIC = `Квота на создание топиков Kafka превышена.`,
  ABYSS_QUOTA_EXCEEDED_FOR_KAFKA_PARTITIONS = `Квота на количество партиций топиков Kafka превышена.`,
  ABYSS_QUOTA_EXCEEDED_FOR_FLOW = `Квота на потоки превышена.`,
  ABYSS_QUOTA_EXCEEDED_FOR_ARCHIVE_INDEX = `Квота на архивный индекс превышена.`,
  ABYSS_QUOTA_EXCEEDED_FOR_ANALYTICAL_INDEX = `Квота на аналитический индекс превышена.`,
  ABYSS_QUOTA_EXCEEDED_FOR_DICTIONARY = `Квота на словари превышена.`,
  ABYSS_QUOTA_EXCEEDED_FOR_LOOKUP = `Квота на lookup'ы превышена.`,

  ABYSS_ANALYTICAL_INDEX_TOO_MANY_STATE_CHANGING_REQUESTS = `Слишком много запросов на изменение.`,

  ABYSS_QUERY_RESULTS_NOT_READY = `Результаты запроса еще не готовы, следует повторить попытку позже.`,
  ABYSS_REQUEST_TIMEOUT = `Истек таймаут запроса.`,

  ABYSS_FULLTEXT_INDEX_INVALID_TYPE = `Нельзя изменить категорию индекса.`,
  ABYSS_FULLTEXT_INDEX_INVALID_SCHEMA = `Не валидная схема.`,
  ABYSS_FULLTEXT_INDEX_INVALID_QUOTA = `Не валидная квота.`,
  ABYSS_INDEX_FORCE_ROTATION_UNAVAILABLE = `Принудительная ротация индекса не возможна, необходимо включить параметр "service.fulltext.rotation.enable"`,
  ABYSS_INVALID_SEARCH_PATTERN = `Не валидный поисковой паттерн.`,
  ABYSS_INVALID_KAFKA_ACL_OPERATION = `Операция с ACL недоступна.`,
  ABYSS_DICTIONARY_VALIDATION_ERROR = `Словарь имеет невалидную структуру.`,
  ABYSS_DICTIONARY_DOES_NOT_CONTAIN_USED_COLUMNS = `Словарь не содержит указанные колонки.`,
  ABYSS_DICTIONARY_COLUMN_USING_IN_LOOKUP = 'Столбец нельзя удалить, так как он входит в состав Lookup.',
  ABYSS_DICTIONARY_SIZE_IS_OVER_LIMIT = `Размер словаря превысил лимит.`,
  ABYSS_DICTIONARY_COLUMNS_DUPLICATES = `Словарь содержит колонки-дубликаты.`,
  ABYSS_INVALID_QUERY_SYNTAX = `Неверная структура SQL-запроса.`,
  ABYSS_COLUMNS_FROM_QUERY_NOT_FOUND = `Колонки из запроса не были найдены в БД.`,
  ABYSS_SCHEMA_FIELDS_INVALID_TYPE_ERROR = `Не удалось изменить тип у столбца.`,
  ABYSS_KAFKA_PARTITIONS_COUNT_IS_INVALID = `Не удалось создать/обновить количество партиций у топика в кафке.`,
  ABYSS_VALIDATION_REQUEST_ERROR = `Во время валидации запроса возникли ошибки.`,
  ABYSS_REQUEST_VALIDATION_ERROR = `Запрос не валидный.`,
  ABYSS_REQUEST_METHOD_NOT_ALLOWED = `HTTP-метод недопустим по указанному endpoint.`,
  ABYSS_MEDIA_TYPE_UNSUPPORTED = `Данный media type не поддерживается.`,
  ABYSS_MEDIA_TYPE_NOT_ACCEPTABLE = `Не удалось принять запрос с данным media type.`,
  ABYSS_SERVLET_PARAMETER_MISSING = `Отсутствует параметр запроса.`,
  ABYSS_SERVLET_REQUEST_BINDING_ERROR = `Произошли фатальные ошибки биндинга.`,
  ABYSS_TYPE_MISMATCHED_ERROR = `Попытка проставить свойство бина неверным типом.`,
  ABYSS_HTTP_MESSAGE_NOT_WRITABLE = `Не удалось сформировать ответ.`,
  ABYSS_SERVLET_REQUEST_PART_MISSING = `Часть ответа не была найдена.`,
  ABYSS_BIND_ERROR = `Произошли фатальные ошибки биндинга.`,
  ABYSS_HTTP_MESSAGE_NOT_READABLE = `Не удалось прочитать тело запроса.`,

  ABYSS_RESTRICTION_VIOLATION = 'Одно из ограничений нарушено.',
  ABYSS_USER_BLOCKED = 'Вы не имеете права запрашивать информацию по этому индексу.',

  ABYSS_INVALID_REQUEST_ERROR = `Невалидное тело запроса.`,

  ABYSS_UNKNOWN_ERROR = 'Неизвестная ошибка',
  ABYSS_HDFS_FILE_MANAGER_ERROR = 'Ошибка файлового менеджера HDFS',
  ABYSS_INCONSISTENT_SERVICE_STATE = 'Несогласованное состояние сервиса',
  ABYSS_QUERY_RESULT_READER_ERROR = 'Ошибка чтения результатов запроса',
  ABYSS_QUERY_EXECUTOR_SERVICE_ERROR = 'Ошибка сервиса выполнения запросов',
  ABYSS_QUERY_FAILED_ERROR = 'Ошибка выполнения запроса',
  ABYSS_QUERY_RESULT_OFFSET_UNREACHABLE = 'Смещение результатов запроса недостижимо',
  ABYSS_SCHEMA_EXTRACTOR_ERROR = 'Ошибка извлечения схемы',
  ABYSS_INTERNAL_CALL_SERVICE_ERROR = 'Ошибка вызова внутреннего сервиса ABYSS',
  ABYSS_RESTRICTION_INTERNAL_PROCESS_ERROR = 'Внутренняя ошибка обработки ограничений',
  ABYSS_BLOCKING_INTERNAL_ERROR = 'Внутренняя ошибка блокировки',
  ABYSS_GROUP_DATA_MISSING = 'Данные группы отсутствуют',
  ABYSS_STREAM_INITIALIZATION_ERROR = 'Ошибка инициализации потока',
  ABYSS_STREAM_PROCESSING_ERROR = 'Ошибка обработки потока',
  ABYSS_FLOW_MANAGER_ERROR = 'Ошибка работы flow manager.',
  ABYSS_FLOW_CONFIG_DELETING_IS_PROHIBITED = 'Нельзя удалить поток, у которого есть экземпляры.',
  ABYSS_SOLR_QUERY_PROCESS_ERROR = `Внутренняя ошибка сервиса полнотекстового индекса.`,
  ABYSS_FULLTEXT_INDEX_ROTATION_ERROR = `Внутренняя ошибка сервиса полнотекстового индекса.`,
  ABYSS_SOLR_CONFIG_SET_ERROR = `Внутренняя ошибка сервиса полнотекстового индекса.`,
  ABYSS_SOLR_CALL_OPERATION_ERROR = `Внутренняя ошибка сервиса полнотекстового индекса.`,
  ABYSS_SOLR_ERROR_RESPONSE = `Внутренняя ошибка сервиса полнотекстового индекса.`,
  ABYSS_FULLTEXT_INDEX_SCHEMA_BUILDER_ERROR = `Внутренняя ошибка сервиса полнотекстового индекса.`,
  ABYSS_RESTRICTION_INTERNAL_ERROR = `Внутренняя ошибка при работе с ограничениями.`,

  ABYSS_VIRTUAL_GROUP_OPERATION_FORBIDDEN = `Для виртуальных групп данная операция недопустима`,

  ABYSS_ACCESS_DENIED_TO_DICTIONARY = `Недостаточно прав для доступа к словарю %i.`,
  ABYSS_DICTIONARY_OPERATION_ERROR = `Внутренняя ошибка при работе со словарями.`,
  ABYSS_DICTIONARY_STREAMING_ERROR = 'Ошибка потоковой обработки словаря',
  ABYSS_CSV_READER_ERROR = 'Ошибка чтения CSV файла',
  ABYSS_LOOKUP_OPERATION_ERROR = 'Ошибка операции с lookup',
  ABYSS_DRUID_INTERNAL_ERROR = 'Ошибка при обращении к Druid. Обратитесь к администратору',
  ABYSS_ANALYTICAL_INDEX_OPERATION_ERROR = 'Ошибка операции с аналитическим индексом',
  ABYSS_ANALYTICAL_INDEX_RESPONSE_STREAM_ERROR = 'Ошибка потока ответа аналитического индекса',
  ABYSS_SQL_FIELDS_TYPE_MAPPER_ERROR = 'Ошибка маппинга типов SQL полей',
  ABYSS_DATASOURCE_MISSING = `Датасорс не найден.`,

  ABYSS_MEMBERSHIP_NOT_FOUND = `Пользователь не состоит в группе.`,
  ABYSS_MEMBERSHIP_ALREADY_EXISTS = `Пользователь уже состоит в группе.`,
  ABYSS_INCOMPATIBLE_SERVICE_MODE = `При текущей конфигурации сервиса запрещена данная операция. Обратитесь к администратору`,

  ABYSS_FULLTEXT_INDEX_OPERATION_ERROR = 'Слишком много меток на полнотекстовый индекс %i.',
  ABYSS_FULLTEXT_INDEX_DUPLICATE_LABELS = 'Метка с таким названием уже добавлена %i.',
  ABYSS_API_KEY_FOR_USER_NOT_FOUND = `API ключ для пользователя %u не найден.`,
  ABYSS_API_KEY_ALREADY_EXISTS = `API ключ уже существует.`,

  ABYSS_FLOW_INSTANCE_ALREADY_STARTED = `Для конфигурации потока используется единая consumer group. Одномоментно экземпляр потока может быть запущен только в 1 зоне. Экземпляр потока уже запущен в другой зоне.`,
  ABYSS_FULLTEXT_INDEX_INSTANCE_ALREADY_EXISTS = `Экземпляр полнотекстового индекса в выбранной зоне уже существует.`,
  ABYSS_FULLTEXT_INDEX_CONFIG_DELETING_IS_PROHIBITED = `Удаление конфиг полнотекстового индекса запрещено`,
  ABYSS_FULLTEXT_INDEX_OVERDRAFT_MAX_TASK_COUNT_REACHED = `Максимально возможное количество полнотекстовых задач с овердрафтом превышено.`,
  ABYSS_FULLTEXT_INDEX_OVERDRAFT_NEGATIVE = `Значение овердрафта не может быть отрицательным.`,

  ABYSS_ZONE_NOT_SUPPORTED = `В данной зоне невозможно создать экземпляр индекса.`,
  ABYSS_ANALYTICAL_INDEX_DELETION_FORBIDDEN = `Удаление аналитического индекса запрещено.`,
  ABYSS_ANALYTICAL_INDEX_CONFIG_NOT_FOUND = `Конфигурация аналитического индекса не найдена.`,
  ABYSS_ANALYTICAL_TASK_INSTANCE_ALREADY_EXISTS = `Экземпляр аналитического индекса в выбранной зоне уже существует.`,
  ABYSS_ANALYTICAL_TASK_INSTANCE_NOT_FOUND = `Экземпляр аналитического индекса не найден`,
  ABYSS_SPANS_NOT_FOUND = `Невозможно найти span для запрошенного id трейса`,
  ABYSS_PROJECT_CHANGE_FORBIDDEN = `Изменение проекта запрещено.`,

  ABYSS_KAFKA_CLUSTER_NOT_FOUND = 'Kafka кластер с данным id не существует',
  ABYSS_KAFKA_CLUSTER_ALREADY_EXISTS = 'Kafka кластер с данным именем уже используется',
  ABYSS_KAFKA_CLUSTER_HAS_ASSOCIATED_TOPICS = 'Имеются привязанные к кластеру топики. Сначала удалите их',
  ABYSS_KAFKA_DEFAULT_CLUSTER_CHANGING_FORBIDDEN = 'Нельзя удалить дефолтный kafka кластер или изменить его статус',
  ABYSS_KAFKA_CLUSTER_IS_NOT_ALLOWED_IN_PROJECT = 'Данный kafka кластер не доступен для этого проекта',
  ABYSS_QUOTA_INCREASING_ERROR = 'Задаваемая квота для проекта превышает максимальную квоту разрешенную в рамках данного кластера kafka',

  ABYSS_TIME_PERIOD_INVALID = 'Недопустимое значение периода времени',

  ABYSS_NOT_ENOUGH_KAFKA_PARTITIONS = 'Для одного или нескольких источников недостаточно партиций для указанного лимита скорости',
  ABYSS_DLQ_TOPIC_CONFLICT = 'DLQ топик Kafka не может совпадать с топиком входящего источника данных',
  ABYSS_ANALYTICAL_INDEX_GLOBAL_CONFIG_AMOUNT_EXCEEDED = 'Невозможно создать новую глобальную конфигурацию, так как максимальное количество глобальных конфигураций достигнуто. Самая старая глобальная конфигурация используется. Удалите неиспользуемые глобальные конфигурации.',
  ABYSS_FLOW_INSTANCE_NOT_FOUND = 'Экземпляр не найден. Обратитесь к администратору.',
  ABYSS_FLOW_CONFIG_NOT_FOUND = 'Конфигурация потока не найдена.',
  ABYSS_FULLTEXT_INDEX_SPLITTING_ERROR = 'Нарушены условия разделения индекса',
  ABYSS_SOLR_REPLICA_PLACEMENT_ERROR = 'Текущие настройки сервера не позволяют выполнить операцию с указанной конфигурацией репликации',
  ABYSS_FULLTEXT_INDEX_INVALID_ADVANCED_PARAMETERS = 'Параллелизм вычитки должен быть меньше или равен количеству партиций топика Kafka. Параллелизм записи должен быть больше или равен параллелизму вычитки.',
  ABYSS_INDEX_KAFKA_SOURCE_CHANGING_PROHIBITED = 'Смена источника данных запрещена',
  ABYSS_UNSUPPORTED_OPERATION = 'Добавление сообщения в топик не может быть выполнено. Фактор репликации топика не соответствует параметру min.insync.replicas кластера. Обратитесь к администратору для изменения конфигурации.',
}
